---
title: "Stat 850 Project Proposal"
format: html
execute:
  echo: false
editor: visual
---

## Data

### Source

```{r}

# Get the Data

tuesdata <- tidytuesdayR::tt_load('2022-05-10')
tuesdata <- tidytuesdayR::tt_load(2022, week = 19)

nyt_titles <- tuesdata$nyt_titles

# Or read in the data manually

nyt_titles <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-10/nyt_titles.tsv')
nyt_full <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-10/nyt_full.tsv')

```

### Description

This dataset contains information about the fiction bestseller list of ***The New York Times*** between the years **1931 to 2020**. This dataset includes the title, author(s), publication date, rank, and other information for every work recorded since the list's founding in 1931.

Every row in the dataset represents a single *"entry"*---that is, a single slot for a particular week---on the list. There will usually be ten or fifteen works listed each week. But the number of bestsellers the Times features in a given week varies, so there may be 3, 6, 7, 8, or 16.

It was collected from ***Tidy Tuesday Archive***. The source link is- https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-05-10/readme.md#nyt_titlestsv

There are 8 variables in nyt_titles and 6 variables in nyt_full. Here is a data dictionary showing each variable, the type of variable, units, and range of values that are possible:

### `nyt_titles`

This is a subset/summary of the larger dataset.

| Variable Name | Type        | Description                      | Units  | Range/Value                                                                  |
|:--------------|:--------------|:--------------|---------------|---------------|
| id            | categorical | Book id                          | NA     | This is random value for each row                                            |
| title         | character   | Title of book                    | NA     | NA                                                                           |
| author        | character   | Author                           | NA     | NA                                                                           |
| year          | double      | Year                             | NA     | years from 1931 to 2020                                                      |
| total_weeks   | numeric     | Total weeks on best sellers list | NA     | no. of frequency of books appear in weeks as best seller. Like 3,4,15,26,... |
| first_week    | numeric     | First week on list (date)        | YYMMDD | date                                                                         |
| debut_rank    | double      | Debut rank on the list           | NA     | numeric value which range from 1 to 17                                       |
| best_rank     | double      | Best rank                        | NA     | numeric value which range from 1 to 17                                       |

### `nyt_full`

| Variable Name | Class     | Description    | Unit   | Range/Value                            |
|:--------------|:--------------|:--------------|---------------|---------------|
| year          | double    | Year           | NA     | years from 1931 to 2020                |
| week          | double    | Week (as date) | YYMMDD | date                                   |
| rank          | double    | Rank (1 \> 18) | NA     | numeric value which range from 1 to 18 |
| title_id      | double    | Title ID       | NA     | This is random value for each row      |
| title         | character | Title of book  | NA     | NA                                     |
| author        | character | Author         | NA     | NA                                     |

## Project Goals

Interesting fact about this dataset is that, book lovers are always curious about what are the bestsellers when selecting the next book to read. As booklovers  it would be exciting for us to explore the below topics to get an overall idea of it. 

We will use NYT Bestseller dataset (From 2000 to 2020) to explore the following topics:

-   How the best rank differs from the debut rank.

-   What is the highest number of weeks that a book got listed as a bestseller over the years 2000-2020.

-   Find about which authors had the highest number of bestsellers (Top 10 or 20 authors)

-   Do books that debut at a higher rank tend to stay on the list longer?

-   Is there a relationship between the length of the title and the debut rank?

We expect to create:

-   Correlation Between Total Weeks and Debut Rank

-   Correlation between length of the title and the debut rank

-   Scatterplot of debut rank and best rank

-   Bar chart showing the distribution of the total weeks on the bestseller list.

-   Bar chart to display the top authors with the most bestsellers.

-   A regression model to see if there is a relationship between the best rank, weeks of some authors who have been repeatedly appearing during 2015-2020.

## Division of Labor

Week of Nov 6 - Working on data preprocessing and working on exploration topics 

Week of Nov 13 - Writing the report (Introduction, Methods, Exploration topics)

Finish the data preprocessing, analysis and part of the report before the project check-in

Week of Nov 20 - Working on the changes based on feedback given and writing the report

Week of Nov 27 - Creating the project presentation and video

Week of Dec 4 - Complete the project report

**Data Analysis**

-   Data preprocessing - Dinuwanthi

-   Graphical analysis - Toma, Dinuwanthi

-   Modeling - Ovini

**Report**

-   Introduction - Toma

-   Methods - Toma 

-   Exploration topics - Dinuwanthi and Ovini

-   Conclusion - Dinuwanthi and Ovini

**Slides and video**

Toma, Dinuwanthi, Ovini

## Additional Comments

Can we change the project goals when we start doing the analysis?

> yes, some modifications to the goals are fine.

The division of labor may change once we start doing the project according to the tasks.

> that's fair. I just wanted you to think about it ahead of time.


-------

Git fame output:

project-team-dot$ git fame .--incl=".(q|Q|r|R)md"
Processing: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 301.86file/s]
Total commits: 4
Total ctimes: 39
Total files: 7
Total loc: 384
| Author                |   loc |   coms |   fils |  distribution   |
|:----------------------|------:|-------:|-------:|:----------------|
| github-classroom[bot] |   281 |      1 |      4 | 73.2/25.0/57.1  |
| Maksuda Aktar Toma    |    40 |      1 |      1 | 10.4/25.0/14.3  |
| DLiyanage24           |    36 |      1 |      1 | 9.4/25.0/14.3   |
| OviniKariyawasam      |    27 |      1 |      1 | 7.0/25.0/14.3   |
